### ISSUE TITLE
Add  Tech conference videos  to index.md . 

### ISSUE THREAD

**Issue by iamkrvikash** [iamkrvikash/conference-talks#1]
## Add your favourite conference videos  to index.md file.

- Go to index.md
- Add your favorite tech talks videos.

⚠️ Note:
Before adding entry `ctrl + f` or `cmd + f` to search and make sure there is not an entry for that video in the index file. You CANNOT enter same  video if you do your PR will not be merged to main.

Steps :
For example you want to in Tech Section
```
 - [Title of the video](link to video) by speaker name.
 
Example - 
- [The mind behind Linux](https://www.youtube.com/watch?v=o8NPllzkFhE) by Linus Torvalds


```

Thanks for Contributing! 👏

**Comment by AbihaFatima** [comment]
@iamkrvikash 
Can I be assigned to do this task?

**Comment by iamkrvikash** [comment]
> @iamkrvikash Can I be assigned to do this task?

Sure @AbihaFatima , Have added you.
